In [108]:
#----------------------------------------------
#This Notebook Cleans the data provided by Zillow
#----------------------------------------------

import pandas as pd
import numpy as np
import os as os

zillow_data = "../Data/Zillow_AllHomes.csv"

In [109]:
#Reads the data file for Zillow
zillow_df = pd.read_csv(zillow_data)

#Removes NA data to prevent issues with merging and charting
zillow_df = zillow_df.dropna(axis = 0)

#Removes the undesired coloumns
del zillow_df["RegionID"]
del zillow_df["City"]
del zillow_df["Metro"]
del zillow_df["SizeRank"]

In [110]:
zillow_df = zillow_df.set_index(['RegionName','CountyName','State'])
zillow_df.head()

,,,1996-04,1996-05,1996-06,1996-07,1996-08,1996-09,1996-10,1996-11,1996-12,1997-01,...,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11
RegionName,CountyName,State,,,,,,,,,,,,,,,,,,,,,
10025,New York County,NY,171600.0,171600.0,171400.0,171200.0,171000.0,171100.0,171300.0,171900.0,173000.0,174500.0,...,1130500,1123700,1119500,1116900,1110100,1098400,1086900,1080500,1072200,1064000
60657,Cook County,IL,158400.0,159700.0,160700.0,161400.0,161700.0,161400.0,160800.0,159800.0,158800.0,157800.0,...,351600,352900,351900,350400,348700,347800,348200,349500,351500,354000
10023,New York County,NY,347900.0,349600.0,351100.0,352500.0,353700.0,354800.0,356000.0,357400.0,359300.0,361900.0,...,1516000,1497900,1497800,1504600,1489900,1463300,1438800,1411600,1389900,1380100
77494,Harris County,TX,210400.0,212200.0,212200.0,210700.0,208300.0,205500.0,202500.0,199800.0,198300.0,197300.0,...,326600,330400,332600,334500,335800,336900,338200,338400,336900,336000
60614,Cook County,IL,192500.0,194500.0,196100.0,197000.0,197200.0,196800.0,195800.0,194400.0,193200.0,192300.0,...,429000,430400,429500,428600,428700,430600,431900,430900,430900,433200

In [112]:
zillow_df_diff = zillow_df_new.groupby(level=0).pct_change(axis = 'columns')
zillow_df_diff.head()

,,,1996-04,1996-05,1996-06,1996-07,1996-08,1996-09,1996-10,1996-11,1996-12,1997-01,...,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11
RegionName,CountyName,State,,,,,,,,,,,,,,,,,,,,,
10025,New York County,NY,NaN,0.000000,-0.001166,-0.001167,-0.001168,0.000585,0.001169,0.003503,0.006399,0.008671,...,-0.004754,-0.006015,-0.003738,-0.002322,-0.006088,-0.010540,-0.010470,-0.005888,-0.007682,-0.007648
60657,Cook County,IL,NaN,0.008207,0.006262,0.004356,0.001859,-0.001855,-0.003717,-0.006219,-0.006258,-0.006297,...,0.006873,0.003697,-0.002834,-0.004263,-0.004852,-0.002581,0.001150,0.003733,0.005722,0.007112
10023,New York County,NY,NaN,0.004886,0.004291,0.003987,0.003404,0.003110,0.003382,0.003933,0.005316,0.007236,...,-0.015840,-0.011939,-0.000067,0.004540,-0.009770,-0.017854,-0.016743,-0.018905,-0.015373,-0.007051
77494,Harris County,TX,NaN,0.008555,0.000000,-0.007069,-0.011391,-0.013442,-0.014599,-0.013333,-0.007508,-0.005043,...,0.011772,0.011635,0.006659,0.005713,0.003886,0.003276,0.003859,0.000591,-0.004433,-0.002671
60614,Cook County,IL,NaN,0.010390,0.008226,0.004589,0.001015,-0.002028,-0.005081,-0.007150,-0.006173,-0.004658,...,0.005390,0.003263,-0.002091,-0.002095,0.000233,0.004432,0.003019,-0.002315,0.000000,0.005338